### ISSUE TITLE
【フロント】i18n化(日本語化)の設定

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#117]
# i18n（日本語化）の設定

## 概要
Railsアプリケーションのデフォルト言語を日本語に設定する。
`gem rails-i18n`を導入し、必要なロケールファイルの配置と読み込み設定を行います。

## TODO
**1. デフォルトの言語を日本語に設定**

- [ ]  `config/application.rb` に以下を追記する。
```
config.i18n.default_locale = :ja
```
***
**2. `gem rails-i18n`のインストール**
`Gemfile`に以下を追加し、`bundle install`を実行する。
```
gem 'rails-i18n', '~> 7.0.0'
```
***
**3. ロケールファイルを `config/locales`以下に配置**

- [ ] `config/locales/activerecord/ja.yml`を作成
- [ ] `config/locales/views/ja.yml`を作成
***

**4. 再起動をする**
- [ ] 上記の設定を再起動`docker compose up`し、取り込む。
***

## 参考記事

- [[初学者]Railsのi18nによる日本語化対応](https://qiita.com/shimadama/items/7e5c3d75c9a9f51abdd5)
