### ISSUE TITLE
【PM】共通フッターの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#141]
## 概要
- 共通フッターの仮作成を行う

## TODO
- [x] `shared/_footer.html.erb`を作成する
- [x] `app/views/layouts/application.html.erb`で上記のファイルをパーシャル化する。
- [x] 仮作成した`shared/_footer.html.erb`に以下を記述
```
<h1>(仮)shared/_footer.html.erb</h1>
```
