### ISSUE TITLE
【PM】お問い合わせの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#142]
## 概要
- お問い合わせページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`contacts#new #create`を追加

**コントローラ**
- [x] `app/controllers/contacts_controller.rb`を作成
- [x] `app/controllers/contacts_controller.rb`に`new`と`create`のアクションを追加

**ビュー**
- [x] `app/views/contacts/new.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/contacts/new.html.erb</h1>
```
