### ISSUE TITLE
【PM】利用規約の仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#143]
## 概要
- 利用規約の仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`terms_of_services#index`を追加

**コントローラ**
- [x] `app/controllers/terms_of_services_controller.rb`を作成
- [x] `app/controllers/terms_of_services_controller.rb`に`index`のアクションを追加

**ビュー**
- [x] `app/views/terms_of_services/index.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/terms_of_services/index.html.erb</h1>
```
