### ISSUE TITLE
【PM】プライバシーポリシーの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#144]
## 概要
- プライバシーポリシーの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`privacy_policies#index`を追加

**コントローラ**
- [x] `app/controllers/privacy_policies_controller.rb`を作成
- [x] `app/controllers/privacy_policies_controller.rb`に`index`のアクションを追加

**ビュー**
- [x] `app/views/privacy_policies/index.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/privacy_policies/index.html.erb</h1>
```
