### ISSUE TITLE
【PM】TOPページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#145]
## 概要
- TOPページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`quiz_posts#index`を追加
このルーティングはrootに設定する

**コントローラ**
- [x] `app/controllers/quiz_posts_controller.rb`を作成
- [x] `app/controllers/quiz_posts_controller.rb`に`index`のアクションを追加

**ビュー**
- [x] `app/views/quiz_posts/index.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/quiz_posts/index.html.erb</h1>
```
