### ISSUE TITLE
【PM】新規クイズ作成ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#146]
## 概要
- 新規クイズ作成ページを行う

## TODO
**ルーティング**
- [x] ルーティングに`quiz_posts#new #crate`を追加

**コントローラ**
- [x] `app/controllers/ quiz_posts_controller.rb`を作成
- [x] `app/controllers/ quiz_posts_controller.rb`に`new`と`create`のアクションを追加

**ビュー**
- [ ] `app/views/quiz_posts/new.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/quiz_posts/new.html.erb</h1>
```
