### ISSUE TITLE
【PM】クイズ詳細ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#159]
## 概要
- クイズ詳細ページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`quiz_posts#show`を追加

**コントローラ**
- [ ] `app/controllers/quiz_posts_controller.rb`を作成
- [x] `app/controllers/quiz_posts_controller.rb`に`show`のアクションを追加

**ビュー**
- [ ] `app/views/quiz_posts/show.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/quiz_posts/show.html.erb</h1>
```
