### ISSUE TITLE
【PM】クイズ回答ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#160]
## 概要
- クイズ回答ページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`questions#show`を追加

**コントローラ**
- [x] `app/controllers/questions_controller.rb`を作成
- [x] `app/controllers/questions_controller.rb`に`show`のアクションを追加

**ビュー**
- [x] `app/views/questions/show.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/questions/show.html.erb</h1>
```
