### ISSUE TITLE
【PM】マイページ（マイアカウント）の仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#162]
## 概要
- マイページ（マイアカウント）の仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`mypages#show`を追加

**コントローラ**
- [x] `app/controllers/mypages_controller.rb`を作成
- [x] `app/controllers/mypages_controller.rb`に`show`のアクションを追加

**ビュー**
- [x] `app/views/mypages/show.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/mypages/show.html.erb</h1>
```
