### ISSUE TITLE
【PM】マイページ（他ユーザのアカウント）仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#163]
## 概要
- マイページ（他ユーザのアカウント）の仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`otherspage#show`を追加

**コントローラ**
- [x] `app/controllers/otherspages_controller.rb`を作成
- [x] `app/controllers/otherspages_controller.rb`に`show`のアクションを追加

**ビュー**
- [x] `app/views/otherspages/show.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/otherspages/show.html.erb</h1>
```
