### ISSUE TITLE
【PM】ブックマークしたクイズ一覧ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#165]
## 概要
- ブックマークしたクイズ一覧ページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに以下を追加
```
resources :quiz_posts do
  collection do
    get :bookmarks
  end
end
```

**コントローラ**
- [x] `app/controllers/quiz_posts_controller.rb`を作成
- [x] `app/controllers/quiz_posts_controller.rb`に`bookmarks`のアクションを追加

**ビュー**
- [x] `app/views/quiz_posts/bookmarks.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/quiz_posts/bookmarks.html.erb</h1>
```
