### ISSUE TITLE
クイズの検索機能

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/programing_quiz#195]
## 概要
検索バーを利用して、クイズタイトル、クイズの作成者、クイズの説明（回答情報を除く）を検索できる機能の作成

## TODO
- [ ] 検索バーを使用して、クイズタイトル、クイズの作成者、クイズの説明（回答情報を除く）を検索できる機能が提供されること。  
- [ ] 検索対象に1文字でも一致するデータが表示されること。  

### **実装内容**

- [ ] ヘッダーに検索バーを設置し、クイズに関する情報を検索。  
- [ ] 検索対象は以下の項目です：
  - クイズタイトル（`title`）  
  - クイズの作成者名（`author_user.name`）  
  - クイズの説明（`answer_source` などのメタ情報）  
- [ ] ユーザーが検索バーに1文字以上入力すると、入力文字を含むクイズがすべて検索結果として表示される。  
- [ ] 回答情報（`choices1` ～ `choices4` や `correct_answer`）は検索対象外です。  

**コントローラー例：**

```ruby
class QuizzesController < ApplicationController
  def index
    if params[:query].present?
      @quizzes = Quiz.joins(:author).where(
        'quizzes.title ILIKE :query OR users.name ILIKE :query OR quizzes.answer_source ILIKE :query',
        query: "%#{params[:query]}%"
      ).distinct
    else
      @quizzes = Quiz.all
    end
  end
end
```

**ビュー例：**

検索フォーム：

```erb
<div class="header-search">
  <%= form_with url: quizzes_path, method: :get, class: 'search-form', local: true do |f| %>
    <%= f.text_field :query, placeholder: '検索するクイズのキーワードを入力...', class: 'search-input' %>
    <%= f.submit '検索', class: 'search-button' %>
  <% end %>
</div>
```

検索結果表示：

```erb
<% if @quizzes.present? %>
  <ul class="quiz-results">
    <% @quizzes.each do |quiz| %>
      <li>
        <%= link_to quiz.title, quiz_path(quiz) %> - 作成者: <%= quiz.author.name %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>該当するクイズが見つかりませんでした。</p>
<% end %>
```

**ルーティング例：**

```ruby
Rails.application.routes.draw do
  resources :quizzes, only: [:index, :show]
end
```
---

---

### **要件**

- [ ] 検索対象は以下の3つの項目とすること：
   - クイズタイトル（`title`）  
   - クイズの作成者名（`author_user.name`）  
   - クイズの説明（`answer_source`）  
- [ ] 回答情報（`choices1` ～ `choices4` や `correct_answer`）は検索対象に含めないこと。  
- [ ] ユーザーが検索バーに1文字以上入力すると、入力文字を含むクイズがすべて表示されること。  
- [ ] 検索結果が存在しない場合、「該当するクイズが見つかりませんでした」と表示されること。
