### ISSUE TITLE
【PM】ランキングページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#200]
## 概要
- ランキングページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`rankings#index`を追加

**コントローラ**
- [x] `app/controllers/rankings_controller.rb`を作成
- [x] `app/controllers/rankings_controller.rb`に`index`のアクションを追加

**ビュー**
- [x] `app/views/rankings/index.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/rankings/index.html.erb</h1>
```
