### ISSUE TITLE
【PM】バッジページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#206]
## 概要
- バッジページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに`badges#index`を追加

**コントローラ**
- [x] `app/controllers/badges_controller.rb`を作成
- [x] `app/controllers/badges_controller.rb`に`index`のアクションを追加

**ビュー**
- [x] `app/views/badges/index.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/badges/index.html.erb</h1>
```
