### ISSUE TITLE
【PM】フォロー一覧ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#207]
## 概要
- バッジページの仮作成を行う

## TODO
**ルーティング**
- [x] ルーティングに以下を記述
```
resources :users do
 get :following 
```

**コントローラ**
- [x] `app/controllers/users_controller.rb`を作成
- [x] `app/controllers/users_controller.rb`に`following`のアクションを追加

**ビュー**
- [x] `app/views/users/following.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/users/following.html.erb</h1>
```
