### ISSUE TITLE
【PM】フォロワー一覧ページの仮作成

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#208]
## 概要
- フォロワー一覧ページの仮作成を行う

## TODO
**ルーティング**
- [ ] ルーティングに以下を記述
```
resources :users do
 get :followers
```

**コントローラ**
- [ ] `app/controllers/users_controller.rb`を作成
- [ ] `app/controllers/users_controller.rb`に`followers`のアクションを追加

**ビュー**
- [ ] `app/views/users/followers.html.erb`を作成し以下を記述
```
<h1>(仮)app/views/users/followers.html.erb</h1>
```
