### ISSUE TITLE
クイズ作成機能

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/programing_quiz#210]
## 概要
クイズ作成ページでクイズの作成ができるようにします
参考資料のURLや画像も投稿できるようにします

## TODO

- [ ]  1. **プルダウンの正解選択**

- 「選択肢」フォームの内容4択の作成とその中から「正解」の選択肢をプルダウンで選択できるようにする。

---

- [ ] 2. **画像アップロード**

- `ActiveStorage` を使用して問題用・解説用の画像をアップロードします。
  - フォームで `file_field` を利用してアップロード可能にします。

---

- [ ]  3. **バリデーション設定**

- モデルで以下のバリデーションを設定：
  - クイズ集タイトル: `length: { maximum: 50 }`、`presence: true`
  - 問題文: `length: { maximum: 1000 }`、`presence: true`
  - 選択肢: `length: { maximum: 250 }`、`presence: true`
  - 解説文: `length: { maximum: 1000 }`、`presence: true`
  - 参考資料（URL）: `format: { with: URI::DEFAULT_PARSER.make_regexp }, presence: true`
  - 画像アップロード: ファイル形式をバリデートする（例: `content_type: { in: %w[image/png image/jpg image/jpeg], message: 'must be a valid image format' }`）。

---

- [ ]  4. **エラーメッセージとフラッシュメッセージ**

  - 入力エラー時に適切なエラーメッセージをユーザーに伝える（例: フラッシュメッセージやリアルタイムバリデーション）。

---

- [ ] 5.  **ページネーションの導入**

- **gem kaminari** を使ったページネーションの導入。

---

- [ ]  6. **Ajax化**

- ページネーションを非同期化するには、`kaminari` の部分テンプレートを `remote: true` を活用して設定します。

---

- [ ] 7.**adminでクイズを30問作れるように場合分け**

- adminだとgeneralと違いクイズを３０問作成できるようにします

#### **1. プルダウンの正解選択**

- [ ] 「選択肢」フォームで4つの選択肢を入力できること。
- [ ] 入力された選択肢の中から、正解をプルダウン形式で選択可能にすること。

---

#### **2. 画像アップロード**

- [ ]  問題用および解説用の画像をアップロード可能にすること。

---

#### **3. バリデーション設定**

- [ ]  各項目に以下のバリデーションを設定すること。

  - **クイズ集タイトル**:
    - 最大50文字以内、必須入力。
  - **問題文**:
    - 最大1000文字以内、必須入力。
  - **選択肢**:
    - 各選択肢の文字数は最大250文字以内、必須入力。
  - **解説文**:
    - 最大1000文字以内、必須入力。
  - **参考資料（URL）**:
    - 有効なURL形式であること、必須入力。
  - **画像アップロード**:
    - 画像のファイル形式は`png`, `jpg`, `jpeg`のいずれかに限定。

---

#### **4. エラーメッセージとフラッシュメッセージ**

- [ ]  バリデーションに違反した場合、エラーメッセージが表示されること。
- [ ] 作成成功時にフラッシュメッセージが表示されること

---

#### **5. ページネーションの導入**

- [ ]  作成済みクイズが１問ずつページネーションで計10問表示されること

---

#### **6. ページネーションのAjax化**

- [ ]  ページ遷移時に全体リロードを行わず、非同期でデータを更新できること。
---
#### **7. adminとgeneralの場合分け**
- [ ] adminで30問、generalで1〜10問のクイズを作成できること

## 参考資料
[rails クイズアプリ作ってみた
](https://qiita.com/Naoya_pro/items/138fe035055c67f926e6)
[[Rails】ajax化とは](https://qiita.com/mmaumtjgj/items/ef494de60a36f2e769b1)
[[Rails]コメント投稿、削除機能のajax化11/20](https://zenn.dev/redheadchloe/articles/e696e5680ca4dc)

##備考

- [ ] クイズ集タイトルとタグに関しては、ページネーションを切り替えても保持されるようにしておいてください
