### ISSUE TITLE
【フロント】動的タイトル（MVPリリース）

### ISSUE THREAD

**Issue by mayu0130** [kogoro06/programing_quiz#44]
# 動的タイトル（MVPリリース部分）の実装

## TODO
動的タイトルの実装
- [ ] MVPリリースで実装する全てのページの動的タイトルの実装を行う。

## 要件
新規登録ページ・ユーザーログインページ・TOPページ・言語別一覧ページ・クイズ詳細ページ・新規クイズ作成ページ・新規クイズ編集ページ・クイズ回答ページ・クイズ解説ページ・マイページ・ユーザー情報更新ページ・ブックマークしたクイズ一覧ページ・お問い合わせページ・プライバシーポリシーページ・利用規約ページの動的タイトルの実装を行う。
***
- [ ] 新規登録ページ → 「`新規登録 | Programming Question`」

- [ ] ユーザーログインページ →「`ユーザーログイン | Programming Question`」

- [ ] TOPページ →「`ようこそ | Programming Question`」

- [ ] 言語別一覧ページ →「`クイズ一覧: #{言語別} | Programming Question`」

- [ ] クイズ詳細ページ →「`クイズ一覧: #{言語別} | Programming Question`」

- [ ] 新規クイズ作成ページ →「`クイズを作成 | Programming Question`」

- [ ] クイズ編集ページ →「`クイズを編集: #{クイズのタイトル} | Programming Question`」

- [ ] クイズ回答ページ →「`クイズに回答中: #{クイズのタイトル} | Programming Question`」

- [ ] クイズ解説ページ →「`クイズの解説: #{クイズのタイトル} | Programming Question`」

- [ ] マイページ →「`マイページ | Programming Question`」

- [ ] ユーザー情報更新ページ →「`アカウント情報の更新 | Programming Question`」

- [ ] ブックマークしたクイズ一覧ページ →「`ブックマーク一覧ページ| Programming Question`」

- [ ] お問い合わせページ → 「`お問い合わせ | Programming Question`」
- [ ] プライバシーポリシーページ → 「`プライバシーポリシー | Programming Question`」
- [ ] 利用規約ページ → 「`利用規約 | Programming Question`」
***
- `#{言語別}` の部分は`HTML`、`CSS`、`JavaScript`、`Rails`、`Git`、`エラー`と動的に表示されるようにする。
- `#{クイズのタイトル}`の部分は対象のクイズのタイトルが動的に表示されるようにする。
